import type { StyleSpecification } from "@maplibre/maplibre-react-native";

interface MapStylePalette {
  readonly border: string;
  readonly borderStrong: string;
  readonly canvas: string;
  readonly land: string;
  readonly muted: string;
  readonly text: string;
  readonly textMuted: string;
}

const attribution = [
  '<a href="https://openfreemap.org/">OpenFreeMap</a>',
  '<a href="https://openmaptiles.org/">© OpenMapTiles</a>',
  'Data from <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
].join(" · ");

export function createMapStyle(
  name: string,
  palette: MapStylePalette,
): StyleSpecification {
  return {
    version: 8,
    name,
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
    sources: {
      openmaptiles: {
        type: "vector",
        url: "https://tiles.openfreemap.org/planet",
        attribution,
      },
    },
    layers: [
      {
        id: "background",
        type: "background",
        paint: {
          "background-color": palette.canvas,
        },
      },
      {
        id: "landuse-residential",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landuse",
        maxzoom: 16,
        filter: ["==", ["get", "class"], "residential"],
        paint: {
          "fill-color": palette.land,
          "fill-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            5,
            0.35,
            12,
            0.8,
          ],
        },
      },
      {
        id: "landuse-industrial",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landuse",
        minzoom: 9,
        filter: [
          "match",
          ["get", "class"],
          ["industrial", "commercial", "retail", "railway"],
          true,
          false,
        ],
        paint: {
          "fill-color": palette.muted,
          "fill-opacity": 0.56,
        },
      },
      {
        id: "landcover",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landcover",
        minzoom: 6,
        filter: [
          "match",
          ["get", "class"],
          ["wood", "grass", "farmland"],
          true,
          false,
        ],
        paint: {
          "fill-color": palette.muted,
          "fill-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            6,
            0.28,
            13,
            0.62,
          ],
        },
      },
      {
        id: "park",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "park",
        paint: {
          "fill-color": palette.muted,
          "fill-opacity": 0.72,
        },
      },
      {
        id: "water",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "water",
        filter: ["!=", ["get", "brunnel"], "tunnel"],
        paint: {
          "fill-antialias": true,
          "fill-color": palette.muted,
        },
      },
      {
        id: "waterway",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        minzoom: 8,
        paint: {
          "line-color": palette.border,
          "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.5, 16, 2.5],
        },
      },
      {
        id: "boundary-region",
        type: "line",
        source: "openmaptiles",
        "source-layer": "boundary",
        minzoom: 4,
        filter: ["==", ["get", "admin_level"], 4],
        paint: {
          "line-color": palette.borderStrong,
          "line-dasharray": [2, 2],
          "line-opacity": 0.42,
          "line-width": ["interpolate", ["linear"], ["zoom"], 4, 0.45, 12, 1],
        },
      },
      {
        id: "boundary-country",
        type: "line",
        source: "openmaptiles",
        "source-layer": "boundary",
        filter: ["==", ["get", "admin_level"], 2],
        paint: {
          "line-color": palette.borderStrong,
          "line-opacity": 0.72,
          "line-width": ["interpolate", ["linear"], ["zoom"], 2, 0.7, 10, 1.5],
        },
      },
      {
        id: "building",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "building",
        minzoom: 13,
        paint: {
          "fill-antialias": true,
          "fill-color": palette.land,
          "fill-outline-color": palette.border,
        },
      },
      {
        id: "road-tunnel-casing",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 8,
        filter: [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            [
              "motorway",
              "trunk",
              "primary",
              "secondary",
              "tertiary",
              "minor",
              "service",
            ],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.border,
          "line-dasharray": [2, 2],
          "line-opacity": 0.7,
          "line-width": [
            "interpolate",
            ["exponential", 1.3],
            ["zoom"],
            8,
            1,
            20,
            24,
          ],
        },
      },
      {
        id: "road-tunnel-inner",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 8,
        filter: [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            [
              "motorway",
              "trunk",
              "primary",
              "secondary",
              "tertiary",
              "minor",
              "service",
            ],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.land,
          "line-dasharray": [2, 2],
          "line-opacity": 0.68,
          "line-width": [
            "interpolate",
            ["exponential", 1.3],
            ["zoom"],
            8,
            0.55,
            20,
            20,
          ],
        },
      },
      {
        id: "road-path",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 13,
        filter: ["==", ["get", "class"], "path"],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.border,
          "line-dasharray": [1, 1.8],
          "line-opacity": 0.82,
          "line-width": ["interpolate", ["linear"], ["zoom"], 13, 0.6, 20, 4],
        },
      },
      {
        id: "road-minor-casing",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 11,
        filter: [
          "all",
          ["!=", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            ["minor", "service", "track"],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.border,
          "line-width": [
            "interpolate",
            ["exponential", 1.25],
            ["zoom"],
            11,
            1,
            20,
            14,
          ],
        },
      },
      {
        id: "road-minor-inner",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 11,
        filter: [
          "all",
          ["!=", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            ["minor", "service", "track"],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.land,
          "line-width": [
            "interpolate",
            ["exponential", 1.25],
            ["zoom"],
            11,
            0.55,
            20,
            11,
          ],
        },
      },
      {
        id: "road-major-casing",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 6,
        filter: [
          "all",
          ["!=", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            ["motorway", "trunk", "primary", "secondary", "tertiary"],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.border,
          "line-width": [
            "interpolate",
            ["exponential", 1.35],
            ["zoom"],
            6,
            0.8,
            20,
            28,
          ],
        },
      },
      {
        id: "road-major-inner",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 6,
        filter: [
          "all",
          ["!=", ["get", "brunnel"], "tunnel"],
          [
            "match",
            ["get", "class"],
            ["motorway", "trunk", "primary", "secondary", "tertiary"],
            true,
            false,
          ],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.land,
          "line-width": [
            "interpolate",
            ["exponential", 1.35],
            ["zoom"],
            6,
            0.45,
            20,
            24,
          ],
        },
      },
      {
        id: "railway-tunnel",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 10,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["==", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.text,
          "line-dasharray": [2, 2],
          "line-opacity": 0.42,
          "line-width": ["interpolate", ["linear"], ["zoom"], 10, 0.7, 20, 2.5],
        },
      },
      {
        id: "railway-service-bed",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 14,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["has", "service"],
          ["!=", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.land,
          "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2, 20, 7],
        },
      },
      {
        id: "railway-service",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 14,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["has", "service"],
          ["!=", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.text,
          "line-opacity": 0.55,
          "line-width": ["interpolate", ["linear"], ["zoom"], 14, 0.6, 20, 1.6],
        },
      },
      {
        id: "railway-main-bed",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 7,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["!", ["has", "service"]],
          ["!=", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.land,
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            7,
            2,
            12,
            4,
            20,
            12,
          ],
        },
      },
      {
        id: "railway-main-ties",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 10,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["!", ["has", "service"]],
          ["!=", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "butt",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.text,
          "line-dasharray": [0.25, 2.1],
          "line-opacity": 0.34,
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            2,
            14,
            4,
            20,
            10,
          ],
        },
      },
      {
        id: "railway-main",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 7,
        filter: [
          "all",
          ["==", ["get", "class"], "rail"],
          ["!", ["has", "service"]],
          ["!=", ["get", "brunnel"], "tunnel"],
        ],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": palette.text,
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            7,
            0.55,
            12,
            1.1,
            20,
            3,
          ],
        },
      },
      {
        id: "label-country",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        maxzoom: 7,
        filter: ["==", ["get", "class"], "country"],
        layout: {
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Bold"],
          "text-letter-spacing": 0.08,
          "text-max-width": 7,
          "text-size": ["interpolate", ["linear"], ["zoom"], 1, 10, 6, 17],
        },
        paint: {
          "text-color": palette.text,
          "text-halo-color": palette.land,
          "text-halo-width": 1.5,
        },
      },
      {
        id: "label-state",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 4,
        maxzoom: 9,
        filter: ["==", ["get", "class"], "state"],
        layout: {
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-letter-spacing": 0.06,
          "text-max-width": 8,
          "text-size": ["interpolate", ["linear"], ["zoom"], 4, 10, 8, 14],
        },
        paint: {
          "text-color": palette.textMuted,
          "text-halo-color": palette.land,
          "text-halo-width": 1.5,
        },
      },
      {
        id: "label-city",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 4,
        filter: ["==", ["get", "class"], "city"],
        layout: {
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Bold"],
          "text-max-width": 8,
          "text-size": ["interpolate", ["linear"], ["zoom"], 4, 12, 11, 19],
        },
        paint: {
          "text-color": palette.text,
          "text-halo-color": palette.land,
          "text-halo-width": 1.5,
        },
      },
      {
        id: "label-settlement",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 7,
        filter: ["match", ["get", "class"], ["town", "village"], true, false],
        layout: {
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-max-width": 8,
          "text-size": ["interpolate", ["linear"], ["zoom"], 7, 11, 13, 14],
        },
        paint: {
          "text-color": palette.text,
          "text-halo-color": palette.land,
          "text-halo-width": 1.5,
        },
      },
      {
        id: "label-neighbourhood",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 11,
        filter: [
          "match",
          ["get", "class"],
          ["suburb", "quarter", "neighbourhood"],
          true,
          false,
        ],
        layout: {
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-letter-spacing": 0.04,
          "text-max-width": 8,
          "text-size": ["interpolate", ["linear"], ["zoom"], 11, 10, 16, 13],
        },
        paint: {
          "text-color": palette.textMuted,
          "text-halo-color": palette.land,
          "text-halo-width": 1.25,
        },
      },
      {
        id: "label-water",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "water_name",
        minzoom: 5,
        layout: {
          "symbol-placement": "line",
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 5, 10, 14, 12],
        },
        paint: {
          "text-color": palette.textMuted,
          "text-halo-color": palette.muted,
          "text-halo-width": 1,
        },
      },
      {
        id: "label-road",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "transportation_name",
        minzoom: 12,
        filter: [
          "match",
          ["get", "class"],
          ["motorway", "trunk", "primary", "secondary", "tertiary", "minor"],
          true,
          false,
        ],
        layout: {
          "symbol-placement": "line",
          "symbol-spacing": 350,
          "text-field": ["coalesce", ["get", "name:latin"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-max-angle": 30,
          "text-size": ["interpolate", ["linear"], ["zoom"], 12, 10, 16, 12],
        },
        paint: {
          "text-color": palette.textMuted,
          "text-halo-color": palette.land,
          "text-halo-width": 1.25,
        },
      },
    ],
  } satisfies StyleSpecification;
}
