export const MAP_LAYER_IDS = {
  base: {
    background: "background",
    boundaryCountry: "boundary-country",
    boundaryRegion: "boundary-region",
    building: "building",
    labelCity: "label-city",
    labelCountry: "label-country",
    labelNeighbourhood: "label-neighbourhood",
    labelRoad: "label-road",
    labelSettlement: "label-settlement",
    labelState: "label-state",
    labelWater: "label-water",
    landcover: "landcover",
    landuseIndustrial: "landuse-industrial",
    landuseResidential: "landuse-residential",
    park: "park",
    railwayMain: "railway-main",
    railwayMainBed: "railway-main-bed",
    railwayMainTies: "railway-main-ties",
    railwayService: "railway-service",
    railwayServiceBed: "railway-service-bed",
    railwayTunnel: "railway-tunnel",
    roadMajorCasing: "road-major-casing",
    roadMajorInner: "road-major-inner",
    roadMinorCasing: "road-minor-casing",
    roadMinorInner: "road-minor-inner",
    roadPath: "road-path",
    roadTunnelCasing: "road-tunnel-casing",
    roadTunnelInner: "road-tunnel-inner",
    water: "water",
    waterway: "waterway",
  },
  milestone: {
    dots: "railway-milestone-dots",
    labels: "railway-milestone-labels",
    selected: "railway-milestone-selected",
  },
  railway: {
    passive: "arow-railway-lines-passive",
    selected: "arow-railway-lines-selected",
  },
  userLocation: "current-location-marker",
} as const;
